### ISSUE TITLE
where does certs_table go?

### ISSUE THREAD

**Issue by aep** [AMDESE/linux-svsm#14]
it looks like most guest tools expect the cert chain  to be returned in the "extended report",
in my case its empty.

but going through the steps in this repo, they are never passed to qemu anywhere, and i don't see where that would even be done.

https://developer.amd.com/wp-content/resources/56421.pdf  says they go in DATA_GPA

but there's no mention of that in the svsm source code

**Comment by tlendacky** [comment]
It is something that will likely need to be done outside of Qemu, since it isn't a per-guest thing, but a HV thing. There is an ioctl available (SNP_SET_EXT_CONFIG) for /dev/sev that can be called on the HV side to supply the certs. Here's an example of what would need to be done: https://github.com/AMDESE/sev-guest/blob/main/src/set-cert-chain.c

**Comment by aep** [comment]
oh i didnt realize this exists because it doesnt compile. https://github.com/AMDESE/sev-guest/issues/23

do you know any alternative tool?

**Comment by tlendacky** [comment]
> oh i didnt realize this exists because it doesnt compile. [AMDESE/sev-guest#23](https://github.com/AMDESE/sev-guest/issues/23)

I know there are issues with that tool, that's why I just pointed you to it as an example of what you could use to code something up.

> 
> do you know any alternative tool?

I don't.
